repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v2.2.3
    hooks:
    -  id: check-ast
    -  id: check-case-conflict
    -  id: check-executables-have-shebangs
    -  id: check-docstring-first
    -  id: check-merge-conflict
    -  id: debug-statements
    -  id: name-tests-test
       args:
            - "--django"
-   repo: https://gitlab.com/pycqa/flake8.git
    rev: 3.7.9
    hooks:
    -  id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy.git
    rev: v0.931
    hooks:
    -  id: mypy
       args:
            - "--install-types"
            - "--non-interactive"
            - "--ignore-missing-imports"
